spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to Prod Environment - Bank Loan Services"
  contactDetails:
    name: "John Smith"
    email: "accounts.support@bank.com"
  onCallSupport:
    - +1-555-0123456
    - +1-555-6543210