spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to QA Environment - Bank Loan Services"
  contactDetails:
    name: "Bob Wilson"
    email: "qa.support@bank.com"
  onCallSupport:
    - +1-999-1234567
    - +1-999-7654321